#ifndef PEAK_PRIVATE_H
#define PEAK_PRIVATE_H

#include <stdint.h>

static const uint8_t PEAK_CAN_ID = 0x6A;
static const uint8_t CYCLEIQ_CAN_ID = 0x6B;

typedef enum {
  PEAK_PACKET_TYPE_BATTERY_STATUS = 0x10,
  PEAK_PACKET_TYPE_BATTERY_ENERGY = 0x11,
  PEAK_PACKET_TYPE_MOTOR_STATUS = 0x12,
  PEAK_PACKET_TYPE_CONTROLLER_STATE = 0x13,
  PEAK_PACKET_TYPE_LIVE_STATUS = 0x14,
  PEAK_PACKET_TYPE_TRIP_PRIMARY = 0x15,
  PEAK_PACKET_TYPE_TRIP_SECONDARY = 0x16,
} peak_packet_type_t;

typedef enum {
  CYCLEIQ_POWER_OFF = 0x00,
  CYCLEIQ_POWER_ON = 0x01,
  CYCLEIQ_COMM_GEAR_SET = 0x02,
  CYCLEIQ_COMM_MODE_SET = 0x03,
  CYCLEIQ_COMM_RIDE_MODE_SET = 0x04,
  CYCLEIQ_COMM_SCREEN_SET = 0x05,
  CYCLEIQ_COMM_CONFIG_GET = 0x06,
  CYCLEIQ_COMM_CONFIG_SET = 0x07,
} cycleiq_command_t;

#endif
